title: אור התורה
description: שיעורי תורה | דברי אלוקים חיים | פרשת שבוע | מחשבה ורוח | וידאו, שמע ומצגות
author: הרב analist0
tagline: "תורת ה' תמימה, משיבת נפש"
lang: he
direction: rtl
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: Asia/Jerusalem

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - vendor

# Social links
social:
  name: analist0
  youtube: https://youtube.com/@analist0
  twitter: https://twitter.com/analist0
  links:
    - https://youtube.com/@analist0
    - https://twitter.com/analist0
