#!/usr/bin/env python3
"""
Enhanced Image Generation for Jekyll Blog Posts
Uses X.AI Grok for image generation + Unsplash/Picsum fallback
"""

import os
import sys
import json
import requests
import hashlib
from datetime import datetime
from pathlib import Path

# Configuration
XAI_API_KEY = os.environ.get('XAI_API_KEY', '')
XAI_API_URL = "https://api.x.ai/v1/images/generations"
XAI_IMAGE_MODEL = "grok-2-image-1212"  # Grok image generation model

UNSPLASH_ACCESS_KEY = os.environ.get('UNSPLASH_ACCESS_KEY', 'YOUR_ACCESS_KEY_HERE')
UNSPLASH_API_URL = "https://api.unsplash.com/search/photos"

# Fallback: Use Picsum for placeholder images (no API key needed)
PICSUM_URL = "https://picsum.photos/1200/630"


def extract_keywords(title: str, description: str = "") -> str:
    """Extract relevant keywords for image search/generation"""
    tech_keywords = {
        'ai': 'artificial intelligence technology futuristic neural networks',
        'ml': 'machine learning data science algorithms',
        'data': 'data science analytics visualization graphs charts',
        'code': 'programming coding software development',
        'web': 'web development internet technology',
        'mobile': 'mobile app smartphone technology',
        'cloud': 'cloud computing servers infrastructure',
        'security': 'cybersecurity hacking encryption',
        'blockchain': 'blockchain cryptocurrency distributed ledger',
        'iot': 'internet of things smart devices connected'
    }

    text = (title + " " + description).lower()

    for key, keywords in tech_keywords.items():
        if key in text:
            return keywords

    return "modern technology innovation digital abstract"


def generate_image_with_grok(title: str, description: str = "") -> dict:
    """
    Generate image using X.AI Grok Vision API

    Args:
        title: Blog post title
        description: Blog post description

    Returns:
        dict: Image information or error
    """

    if not XAI_API_KEY:
        print("⚠️  XAI_API_KEY not set, falling back to Unsplash/Picsum")
        return None

    try:
        keywords = extract_keywords(title, description)

        # Create detailed image prompt
        prompt = f"""Create a professional, high-quality hero image for a technology blog post.

Title: {title}
Description: {description}

Image requirements:
- Modern and sleek design
- Technology-focused theme with {keywords}
- Professional and clean aesthetic
- Suitable for blog header (16:9 ratio, 1200x630)
- High resolution and eye-catching
- Colors: Tech blues, purples, or modern gradients
- Style: Abstract, futuristic, professional

The image should be visually stunning and immediately grab attention while being relevant to the topic."""

        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {XAI_API_KEY}"
        }

        payload = {
            "model": XAI_IMAGE_MODEL,
            "prompt": prompt,
            "n": 1
        }

        print("🎨 Generating image with Grok Image API...")
        response = requests.post(XAI_API_URL, headers=headers, json=payload, timeout=60)
        response.raise_for_status()

        data = response.json()

        # Check for API error response
        if 'error' in data:
            print(f"⚠️  Grok API error: {data['error']}")
            return None

        # Image generation API returns data array with URLs
        if 'data' in data and len(data['data']) > 0:
            image_url = data['data'][0].get('url', '')
            if image_url:
                return {
                    'success': True,
                    'image_url': image_url,
                    'source': 'grok-image',
                    'model': XAI_IMAGE_MODEL,
                    'photographer': 'AI Generated by Grok',
                    'photographer_url': 'https://x.ai'
                }

        print("⚠️  Grok didn't return image URL, trying Unsplash...")
        return None

    except Exception as e:
        print(f"⚠️  Grok API error: {e}")
        return None


def get_image_from_unsplash(title: str, description: str = "") -> dict:
    """
    Search and download image from Unsplash

    Args:
        title: Blog post title
        description: Blog post description

    Returns:
        dict: Image information (URL, photographer, etc.)
    """

    if UNSPLASH_ACCESS_KEY == 'YOUR_ACCESS_KEY_HERE':
        # Fallback to Picsum (no API needed)
        return {
            'success': True,
            'image_url': f"{PICSUM_URL}?random={hashlib.md5(title.encode()).hexdigest()[:8]}",
            'source': 'picsum',
            'photographer': 'Picsum Photos',
            'photographer_url': 'https://picsum.photos',
            'download_url': None
        }

    try:
        # Extract search keywords
        keywords = extract_keywords(title, description)

        params = {
            'query': keywords,
            'per_page': 1,
            'orientation': 'landscape',
            'content_filter': 'high'
        }

        headers = {
            'Authorization': f'Client-ID {UNSPLASH_ACCESS_KEY}'
        }

        response = requests.get(UNSPLASH_API_URL, params=params, headers=headers, timeout=10)
        response.raise_for_status()

        data = response.json()

        if data.get('results') and len(data['results']) > 0:
            photo = data['results'][0]

            return {
                'success': True,
                'image_url': photo['urls']['regular'],
                'image_download': photo['urls']['download'],
                'source': 'unsplash',
                'photographer': photo['user']['name'],
                'photographer_url': photo['user']['links']['html'],
                'description': photo.get('description', photo.get('alt_description', '')),
                'color': photo.get('color', '#000000')
            }
        else:
            # Fallback to Picsum
            return {
                'success': True,
                'image_url': f"{PICSUM_URL}?random={hashlib.md5(title.encode()).hexdigest()[:8]}",
                'source': 'picsum_fallback',
                'photographer': 'Picsum Photos',
                'photographer_url': 'https://picsum.photos'
            }

    except Exception as e:
        print(f"⚠️  Unsplash API error: {e}")
        # Fallback to Picsum
        return {
            'success': True,
            'image_url': f"{PICSUM_URL}?random={hashlib.md5(title.encode()).hexdigest()[:8]}",
            'source': 'picsum_error_fallback',
            'photographer': 'Picsum Photos',
            'photographer_url': 'https://picsum.photos',
            'error': str(e)
        }


def get_best_image(title: str, description: str = "") -> dict:
    """
    Try multiple image sources in order:
    1. Grok Vision (AI generated)
    2. Unsplash (professional photos)
    3. Picsum (placeholder)
    """

    # Try Grok first
    grok_result = generate_image_with_grok(title, description)
    if grok_result and grok_result.get('success'):
        print("✅ Using AI-generated image from Grok")
        return grok_result

    # Try Unsplash/Picsum
    print("📸 Falling back to photo search...")
    return get_image_from_unsplash(title, description)


def update_post_frontmatter(post_path: str, image_data: dict) -> bool:
    """
    Update Jekyll post frontmatter with image and SEO data

    Args:
        post_path: Path to the Jekyll post file
        image_data: Image information dictionary

    Returns:
        bool: Success status
    """

    try:
        with open(post_path, 'r', encoding='utf-8') as f:
            content = f.read()

        if not content.startswith('---'):
            print(f"❌ Invalid post format (no frontmatter): {post_path}")
            return False

        parts = content.split('---', 2)
        if len(parts) < 3:
            print(f"❌ Invalid frontmatter format: {post_path}")
            return False

        frontmatter_lines = parts[1].strip().split('\n')
        body = parts[2]

        # Update/add image field
        has_image = False
        new_lines = []

        for line in frontmatter_lines:
            if line.strip().startswith('image:'):
                new_lines.append(f'image: "{image_data["image_url"]}"')
                has_image = True
            else:
                new_lines.append(line)

        if not has_image:
            new_lines.append(f'image: "{image_data["image_url"]}"')

        # Add image credit if available
        if 'photographer' in image_data and 'image_credit:' not in '\n'.join(new_lines):
            credit = f"{image_data['photographer']} via {image_data['source'].title()}"
            new_lines.append(f'image_credit: "{credit}"')
            new_lines.append(f'image_credit_url: "{image_data.get("photographer_url", "")}"')

        # Rebuild frontmatter
        new_frontmatter = '\n'.join(new_lines)
        new_content = f'---\n{new_frontmatter}\n---{body}'

        with open(post_path, 'w', encoding='utf-8') as f:
            f.write(new_content)

        print(f"✅ Updated post: {post_path}")
        return True

    except Exception as e:
        print(f"❌ Error updating post: {e}")
        return False


def main():
    """Main function"""

    if len(sys.argv) < 2:
        print("""
╔══════════════════════════════════════════════════════════════╗
║       Enhanced Image Generator for Jekyll Posts             ║
╚══════════════════════════════════════════════════════════════╝

Usage:
  python3 generate_ai_image.py <post-file>
  python3 generate_ai_image.py --test "Title" "Description"

Features:
  ✅ AI-generated images with Grok Vision (grok-2-image-1212)
  ✅ High-quality photos from Unsplash
  ✅ Automatic fallback to Picsum (no API key needed)
  ✅ Smart keyword extraction
  ✅ SEO-friendly image credits
  ✅ Automatic frontmatter update

Image Sources (in priority order):
  1. Grok Vision - AI-generated custom images
  2. Unsplash - Professional stock photos
  3. Picsum - Placeholder images (always works)

Examples:
  # Generate image for existing post
  python3 generate_ai_image.py _posts/2025-12-04-my-post.md

  # Test mode
  python3 generate_ai_image.py --test "AI Revolution" "How AI changes everything"

Environment Variables:
  XAI_API_KEY - X.AI API key (for Grok image generation)
  UNSPLASH_ACCESS_KEY - Unsplash API key (optional, for better photos)

Current Status:
  XAI_API_KEY: {'✅ Set' if XAI_API_KEY else '❌ Not set'}
  UNSPLASH_ACCESS_KEY: {'✅ Set' if UNSPLASH_ACCESS_KEY != 'YOUR_ACCESS_KEY_HERE' else '⚠️  Not set'}
        """)
        sys.exit(1)

    # Test mode
    if sys.argv[1] == '--test':
        title = sys.argv[2] if len(sys.argv) > 2 else "Test Blog Post About Technology"
        description = sys.argv[3] if len(sys.argv) > 3 else "An amazing technology article"

        print(f"\n🧪 Testing Image Generation...")
        print(f"📝 Title: {title}")
        print(f"📄 Description: {description}")
        print(f"🔍 Keywords: {extract_keywords(title, description)}\n")

        result = get_best_image(title, description)
        print(json.dumps(result, indent=2, ensure_ascii=False))
        sys.exit(0)

    # Post mode
    post_path = sys.argv[1]

    if not os.path.exists(post_path):
        print(f"❌ Post file not found: {post_path}")
        sys.exit(1)

    # Parse post
    with open(post_path, 'r', encoding='utf-8') as f:
        content = f.read()

    try:
        parts = content.split('---', 2)
        frontmatter = parts[1]

        title = ""
        description = ""

        for line in frontmatter.split('\n'):
            line = line.strip()
            if line.startswith('title:'):
                title = line.split(':', 1)[1].strip().strip('"\'')
            elif line.startswith('description:'):
                description = line.split(':', 1)[1].strip().strip('"\'')

        if not title:
            print(f"❌ No title found in post frontmatter")
            sys.exit(1)

        print(f"\n🎨 Generating image for post...")
        print(f"📝 Title: {title}")
        print(f"📄 Description: {description}")
        print(f"🔍 Keywords: {extract_keywords(title, description)}\n")

        result = get_best_image(title, description)

        if result['success']:
            print(f"✅ Image selected successfully!")
            print(f"🖼️  URL: {result['image_url']}")
            print(f"📷 Source: {result['source']}")
            print(f"👤 Credit: {result.get('photographer', 'N/A')}\n")

            if update_post_frontmatter(post_path, result):
                print(f"✅ Post updated with image and credits")
            else:
                print(f"⚠️  Please add image manually:")
                print(f"   image: \"{result['image_url']}\"")
        else:
            print(f"❌ Image generation failed")
            sys.exit(1)

    except Exception as e:
        print(f"❌ Error processing post: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()
